name: Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pwd
          ls -l
          pytest --version
          which pytest
          pytest -vvv --cov=./flake8_required_keyword_arguments --cov-report=xml:./coverage.xml --cov-report term-missing --cov-fail-under=80
      - name: Linting
        run: |
          black --line-length 119 --check --diff .
          isort --check-only --diff .
          flake8 flake8_required_keyword_arguments
          pylint --rcfile=.pylintrc flake8_required_keyword_arguments
          codespell flake8_required_keyword_arguments tests
          find . -name '*.py' -exec pyupgrade {} +
      - name: Typecheck with mypy
        run: mypy . --ignore-missing-imports --disallow-untyped-defs
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: flake8-required-keyword-arguments
          flags: unittests
          env_vars: OS,PYTHON
